### PR TITLE
delete account instructions

### PR DESCRIPTION
**Pull request by dtrdic**

### CODE REVIEW

**Comment by icarusdust** [comment]
Is adding apps to CM page a correct place for this info ?

**Comment by dtrdic** [comment]
> Is adding apps to CM page a correct place for this info ?

yes I agree, actually not a good spot for that information.. Can I rather move it [here](https://docs.codemagic.io/getting-started/teams/#deleting-the-team)? below deleting team heading

**Comment by icarusdust** [comment]
Maybe let's add it to [FAQ's page ](https://docs.codemagic.io/getting-started/faq/)? Deleting a team should be different than deleting account

**Comment by icarusdust** [comment]
Also, if they need us to delete any chat threads related to their account, they will need to reach out to us.

**Review by icarusdust — APPROVED** [review]
LGTM

**Pull request merged**
