### PR TITLE
separated instructions for wfe and yaml for uploading dSYM file to Firebase

### PR DESCRIPTION
**Pull request by dtrdic**
added a separate, much more visible step for uploading dSYM file to Firebase, since we have a lot of queries on how to do it with wfe

### CODE REVIEW

**Comment by icarusdust** [comment]
Why do we want to duplicate the script ? I mean it says add the script to post-publishing step in the WFE and in yaml.

**Comment by dtrdic** [comment]
> Why do we want to duplicate the script ? I mean it says add the script to post-publishing step in the WFE and in yaml.

many users don't notice that sentence, they just see that is about yaml file, and stop reading further. This was the reason I decided to make it more obvious. I can close this pr if you don't agree

**Comment by icarusdust** [comment]
Let's see how it looks then

**Review by icarusdust — APPROVED** [review]
lgtm

**Pull request merged**
