### PR TITLE
ensure keystore has JKS format

### PR DESCRIPTION
**Pull request by icarusdust**

### CODE REVIEW

**Comment by mikhail-tokarev** [comment]
see https://codemagicio.slack.com/archives/CEKE2KZ37/p1623685985110100 for more information

**Review by VeArnold — CHANGES_REQUESTED** [review]
I think it might be better to keep the formatting snake_case and a bit more meaningful as per other examples. Any particular reason to renaming the jks file to upload-keystore? Perhaps keep it keystore_name or change it to upload_keystore. As for the alias, perhaps revert back to alias_name too?

**Comment by icarusdust** [comment]
Sure thing. Committing the changes as suggested. No, there is no particular reason for renaming to upload-keystore.

**Review by VeArnold — APPROVED** [review]
LGTM, thanks for your contribution! :)

**Pull request merged**
